export const APP_NAME = import.meta.env.VITE_APP_NAME || 'PayStream'
export const APP_VERSION = import.meta.env.VITE_APP_VERSION || '1.0.0'
export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
export const DEFAULT_THEME = 'light'
export const TOKEN_STORAGE_KEY = 'PayStream_token'
export const REFRESH_TOKEN_KEY = 'PayStream_refresh'
export const THEME_STORAGE_KEY = 'PayStream-theme'

export const STELLAR_NETWORK = import.meta.env.VITE_STELLAR_NETWORK || 'testnet'
export const STELLAR_NETWORK_PASSPHRASE = import.meta.env.VITE_STELLAR_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015'
export const SOROBAN_RPC_URL = import.meta.env.VITE_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org'
export const SOROBAN_CONTRACT_ID = import.meta.env.VITE_SOROBAN_CONTRACT_ID || ''
export const EXPLORER_URL = import.meta.env.VITE_EXPLORER_URL || 'https://stellar.expert/explorer/testnet'
export const FREIGHTER_DOWNLOAD_URL = import.meta.env.VITE_FREIGHTER_DOWNLOAD_URL || 'https://freighter.app'
